version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: "./docker/Dockerfile"
    container_name: php_basel_playground
    depends_on:
      - nginx
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  nginx:
    image: nginx:1.19-alpine
    container_name: php-nginx
    restart: always
    ports:
      - 8008:80
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d