#!/usr/bin/env php
<?php

define('RUN_START', microtime(true));

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
|
*/
$app = require __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run Console Kernel Then Handel the Command
|--------------------------------------------------------------------------
|
|
*/

$kernel = $app->make('Illuminate\Contracts\Console\Kernel');


$status = $kernel->handle($input = new ArgvInput, new ConsoleOutput);


/*
|--------------------------------------------------------------------------
| Shutdown The Console
|--------------------------------------------------------------------------
|
*/

$kernel->terminate($input, $status);


exit($status);
